### ISSUE TITLE
support DNS records which are configured via `*`

### ISSUE THREAD

**Issue by aellwein** [aellwein/cert-manager-webhook-netcup#1]
_Originally posted by @DerKnerd in https://github.com/cert-manager/cert-manager/issues/4885#issuecomment-1110712109_

> Could you maybe extend it to support DNS records which are configured via `*`?

@DerKnerd Of course. I will test it, but i need to do modify my configuration first. Please stay tuned ;-)

**Comment by DerKnerd** [comment]
I think I found what part of the code causes the issue, but I am not 100% sure. In the method `addOrDeleteTxtRecord` you return the error if `sess.InfoDnsRecords(domainName)` fails. I guess, that the response fails since there are no records of that domain since it is not configured in netcup. The best solution would, probably, be a config value which allows to ignore the error and just continues.

**Comment by aellwein** [comment]
Very nice, thanks!

**Comment by aellwein** [comment]
@DerKnerd just tell me if i can support you with something.

**Comment by DerKnerd** [comment]
@aellwein you could check the PR I opened :slightly_smiling_face: I have it running on my server and works like a charm.

**Comment by aellwein** [comment]
Thank you, i'll check it. Funny, that i didn't receive any notifications about new PR.
