### ISSUE TITLE
"helm install" of the helm chart leads to certificate error

### ISSUE THREAD

**Issue by hweistdev** [aellwein/cert-manager-webhook-netcup#62]
Hi and thank you for your work on this helm-chart. That's exactly what I need. When I execute 
"helm install my-cert-manager-webhook-netcup cert-manager-webhook-netcup/cert-manager-webhook-netcup --namespace cert-manager", 

I get the error-message "* Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-06-03T05:12:52Z is after 2024-06-01T09:43:35Z"

<img width="2027" alt="image" src="https://github.com/aellwein/cert-manager-webhook-netcup/assets/17140348/cfa7a55c-5398-4716-b505-46868dc5a339">

What can be done to fix this?

Thank you very much!

Best regards,
Hendrik

**Comment by aellwein** [comment]
Hello @hweistdev, 
thanks for reporting this, first of all, what version of cert-manager do you use?

Small note: there was a [similar issue](https://github.com/cert-manager/cert-manager/issues/4771) that suggests an incorrect certificate generation within older cert-manager installations. In particular, the error message suggests that a certificate issued for the webhook has a wrong timestamp for its validity range. I cannot tell an exact reason for this, since
the internal certificate is generated by the cert-manager itself, the webook is not involved in this.

Can you maybe try if the [suggested workaround](https://github.com/cert-manager/cert-manager/issues/4771#issuecomment-1076867717) helps in your situation?

**Comment by hweistdev** [comment]
Hello @aellwein,
I thought I was using the last version of cert-manager (v14.4). But I wasn't sure any more if I installed it correctly. So, I deleted my resources in the kubernetes-installation on my laptop and reinstalled cert-manager completely. Now, it works. Thank you very much!

<img width="1206" alt="image" src="https://github.com/aellwein/cert-manager-webhook-netcup/assets/17140348/15cf36ef-d793-41d1-bb1d-47e5c5004dc3">

Best regards,
Hendrik
