### ISSUE TITLE
How to request wildcards for subdomains

### ISSUE THREAD

**Issue by itsyoshio** [aellwein/cert-manager-webhook-netcup#7]
i own a domain `example.com`.

In an Ingress i'd like to run the DNS01 Challenge for a host `*.app.example.com`. \
When i do this, the netcup webhook isn't able to find the resource `app.example.com` since i only have `example.com`.

Is there a specific workflow for this?

**Comment by aellwein** [comment]
@itsyoshio you also own DNS zone ``app`` inside the ``example.com`` domain, right?  
This is required, because the webhook needs to create TXT records inside the ``app`` DNS zone to response ACME challenges. 

If this is already the case, can you please elaborate more on the configuration and possibly the log output of the 
webhook pod to understand what is going on there?

**Comment by aellwein** [comment]
Thanks for the explanation!
